spring:
  application:
    name: booking-bot
  config:
    import: "application-db.yml"

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

google:
  table:
    credentials-path: ${GOOGLE_CREDENTIALS_PATH}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO
    org.telegram: WARN
